CREATE TABLE `SUBJECT` (
	`SCHOOL_CD` CHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
	`SUBJECT_CD` CHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
	`SUBJECT_NAME` VARCHAR(020) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
	PRIMARY KEY (`SCHOOL_CD`,`SUBJECT_CD`)
) ENGINE=InnoDB;